function [ reachSTATS ] = computeReachSTATS(    reachFLOWobj, ...
                                                demGRIDobj, ...
                                                flowAccumulationFLOWobj, ...
                                                flowDirectionFLOWobj, ...
                                                reachSHAPEstruct, ...
                                                slopeGRIDobj, ...
                                                aspectGRIDobj, ...
                                                adjacencyMatrix )
%UNTITLED8 Summary of this function goes here
%   Detailed explanation goes here


end

