function [ reachSTATS ] = reachSTATS(    reachFLOWobj, ...
                                            demGRIDobj, ...
                                            flowAccumulationFLOWobj, ...
                                            flowDirectionFLOWobj, ...
                                            reachSHAPEstruct )
%UNTITLED8 Summary of this function goes here
%   Detailed explanation goes here


end

